apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalogue-service
  name: catalogue-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalogue-service
  template:
    metadata:
      labels:
        app: catalogue-service
    spec:
      containers:
      - name: catalogue-service
        image: CONTAINER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        
