apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: catalogue-service
  name: catalogue-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalogue-service
  template:
    metadata:
      labels:
        app: catalogue-service
    spec:
      containers:
      - name: catalogue-service
        image: 361612195873.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo:${env.BUILD_NUMBER}
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalogue-service
    k8s-app: catalogue-service
  name: catalogue-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: catalogue-service
