apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
  labels:
    app: catalogue-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: catalogue-service
    
